model:
    type: "keyword"
    label: "yoda"
    repeat: 32
    batch_size: 2
    epochs: 2

    save_path: "s3://yoda-tiny-set/models/yodadetector1/model-snaphot"
    results_path: "s3://yoda-tiny-set/models/yodadetector1/model-snaphot/results.json"

dataset:
    path: "s3://yoda-tiny-set/exports/ab7d1f4a83bb87247a2bb83f41567813.jsonlines"

verbose: True
verbose_info: True

aws_region: us-east-1